Adding an option for apps to 'forecall' callContractWithToken to hasten resolution of calls.
axelarnetwork/axelar-cgp-solidity pull request #102
Opened 2022-05-24 19:11 UTC by Foivos

Add a different version of the executable that can have executeWithToken front-run by the application (and have the tokens provided to it) to hasten execution.

2022-05-26 16:46 UTC, sammy1991106 commented
I need more information about what is this PR doing and what are we trying to achieve before I can review it.

2022-06-02 11:58 UTC, sammy1991106 submitted a review, later dismissed

2022-06-02 11:58 UTC, sammy1991106 commented on test/Util.js
> +const { it } = require('mocha');
```suggestion
```

2022-06-02 11:58 UTC, sammy1991106 commented on src/interfaces/IAxelarExecutableForetellable.sol
> +    mapping(string => mapping(string => mapping(bytes => mapping(string => mapping(uint256 => address)))))
```suggestion
    mapping(bytes32 => address) public foretellers;
```
and key becomes keccak256(sourceChain, sourceAddress, payload, tokenSymbol, amount). Fewer hashing happening and therefore cheaper gas cost, no?

2022-06-02 11:58 UTC, sammy1991106 commented on src/gmp-test/DestinationChainSwapExecutableForetellable.sol
> +        (string memory tokenSymbolB, string memory recipient) = abi.decode(payload, (string, string));
```suggestion
        (bytes32 nonce, string memory tokenSymbolB, string memory recipient) = abi.decode(payload, (string, string));
```
Without a nonce, only one of the multiple swapping attempts with the exact same parameters can be foretold until executed.

2022-06-02 11:58 UTC, sammy1991106 commented on src/interfaces/IAxelarExecutableForetellable.sol
> +    function foretell(
I don't see why foretell can only work with executeWithToken but not execute?

2022-06-06 20:24 UTC, re1ro commented
Please rebase your branch onto the latest main 💯

2022-06-06 20:26 UTC, re1ro commented on src/interfaces/IAxelarExecutableForetellable.sol
> +abstract contract IAxelarExecutableForetellable {
@sammy1991106 we already used that pattern for the `IAxelarExecutable`. It has some logic in it and also is an abstract contract. Do you think it's worth renaming it? Also should it be moved out of `interfaces` folder?

2022-06-06 21:08 UTC, sammy1991106 commented on src/interfaces/IAxelarExecutableForetellable.sol
> +abstract contract IAxelarExecutableForetellable {
ok nvm then if it's already done elsewhere.

2022-06-07 18:24 UTC, re1ro requested changes

2022-06-07 18:24 UTC, re1ro commented on contracts/interfaces/IAxelarExecutableForetellable.sol
> +        _execute(sourceChain, sourceAddress, payload);
Is this `_execute` duplicated here?

2022-06-07 18:24 UTC, re1ro commented on contracts/interfaces/IAxelarExecutableForetellable.sol
> +        IERC20(token).transferFrom(msg.sender, address(this), amount);
We need to use safe transfer here
[Example](https://github.com/axelarnetwork/axelar-cgp-solidity/blob/main/contracts/gas-service/AxelarGasService.sol#L158)

2022-06-07 19:28 UTC, re1ro approved these changes

2022-06-07 19:29 UTC, merged