feature(AxelarAuthWeighted): weighted multisig
axelarnetwork/axelar-cgp-solidity pull request #124
Opened 2022-07-09 23:53 UTC by re1ro

* [x] AxelarAuthWeighted: weighted multisig auth module
* [x] Unit tests

2022-07-10 23:34 UTC, sergeynog submitted a review, later dismissed

2022-07-10 23:34 UTC, sergeynog commented on contracts/auth/AxelarAuthWeighted.sol
> +            if (weight >= threshold) return;
note: double check with off by one against the core.

2022-07-13 15:09 UTC, sammy1991106 requested changes

2022-07-13 20:05 UTC, re1ro commented on contracts/auth/AxelarAuthMultisig.sol
> +        if (newThreshold == 0 || operatorsLength < newThreshold) revert InvalidThreshold();
It's an error check. If it's less we revert the transaction

2022-07-13 20:19 UTC, re1ro commented on contracts/auth/AxelarAuthWeighted.sol
> +    constructor(bytes[] memory recentOperators) AxelarAuthMultisig(recentOperators) {}
Yeah each bytes item in `bytes[]` has it encoded

2022-07-14 15:55 UTC, merged